# Generated by Django 6.0.4 on 2026-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itempost_latitude_itempost_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
